interface Node { id: string; label: string; type: string; technology: string }
interface Edge { source: string; target: string; label?: string }
interface Graph { nodes: Node[]; edges: Edge[]; summary: string; tech_stack: string[]; confidence: number }
interface Dimension { score: number; evidence: string[] }
interface Bench { overall: number; grade: string; dimensions: Record<string, Dimension> }
interface DiffSummary { severity: string; added: number; removed: number; changed: number; description: string }
interface Diff { summary: DiffSummary; added_nodes: Node[]; removed_nodes: Node[] }

interface CommentInput {
  graph: Graph;
  bench: Bench;
  diff: Diff | null;
  shareUrl?: string;
  repoUrl: string;
  tier: string;
}

const GRADE_EMOJI: Record<string, string> = { A: "🟢", B: "🔵", C: "🟡", D: "🟠", F: "🔴" };
const SEV_EMOJI: Record<string, string> = { none: "✅", low: "🔵", medium: "🟡", high: "🟠", critical: "🔴" };

const DIM_LABEL: Record<string, string> = {
  resilience: "Resilience",
  observability: "Observability",
  security: "Security",
  scalability: "Scalability",
  simplicity: "Simplicity",
  async_coverage: "Async Coverage",
};

function scoreBar(score: number): string {
  const filled = Math.round(score / 10);
  return "█".repeat(filled) + "░".repeat(10 - filled) + ` ${score}/100`;
}

function gradeSection(bench: Bench): string {
  const emoji = GRADE_EMOJI[bench.grade] ?? "⚪";
  const lines: string[] = [
    `## ${emoji} Architecture Grade: **${bench.grade}** — ${bench.overall}/100`,
    "",
    "| Dimension | Score | Top Finding |",
    "|-----------|-------|-------------|",
  ];

  const order = ["resilience", "observability", "security", "scalability", "simplicity", "async_coverage"];
  for (const key of order) {
    const dim = bench.dimensions[key];
    if (!dim) continue;
    const label = DIM_LABEL[key] ?? key;
    const top = dim.evidence[0] ?? "—";
    lines.push(`| ${label} | \`${scoreBar(dim.score)}\` | ${top} |`);
  }

  return lines.join("\n");
}

function graphSection(graph: Graph): string {
  const nodeTypes = graph.nodes.reduce<Record<string, number>>((acc, n) => {
    acc[n.type] = (acc[n.type] ?? 0) + 1;
    return acc;
  }, {});

  const typeSummary = Object.entries(nodeTypes)
    .map(([t, c]) => `${c} ${t}`)
    .join(", ");

  const stack = graph.tech_stack.slice(0, 8).join(", ");
  const conf = Math.round(graph.confidence * 100);

  return [
    "## 🗺️ Architecture Snapshot",
    "",
    `> ${graph.summary}`,
    "",
    `**Components:** ${graph.nodes.length} nodes (${typeSummary}) · ${graph.edges.length} edges`,
    `**Tech stack:** ${stack}`,
    `**AI confidence:** ${conf}%`,
  ].join("\n");
}

function diffSection(diff: Diff): string {
  const { summary, added_nodes, removed_nodes } = diff;
  const emoji = SEV_EMOJI[summary.severity] ?? "⚪";
  const lines: string[] = [
    `## ${emoji} Architecture Diff — Severity: **${summary.severity.toUpperCase()}**`,
    "",
    `${summary.description}`,
    "",
    `| Change | Count |`,
    `|--------|-------|`,
    `| ➕ Added components | ${summary.added} |`,
    `| ➖ Removed components | ${summary.removed} |`,
    `| 🔀 Changed connections | ${summary.changed} |`,
  ];

  if (added_nodes.length > 0) {
    lines.push("", "**New components:**");
    for (const n of added_nodes.slice(0, 5)) {
      lines.push(`- \`${n.label}\` (${n.type} · ${n.technology})`);
    }
    if (added_nodes.length > 5) lines.push(`- _...and ${added_nodes.length - 5} more_`);
  }

  if (removed_nodes.length > 0) {
    lines.push("", "**Removed components:**");
    for (const n of removed_nodes.slice(0, 5)) {
      lines.push(`- \`${n.label}\` (${n.type} · ${n.technology})`);
    }
    if (removed_nodes.length > 5) lines.push(`- _...and ${removed_nodes.length - 5} more_`);
  }

  return lines.join("\n");
}

export function buildComment(input: CommentInput): string {
  const { graph, bench, diff, shareUrl } = input;

  const sections: string[] = [
    "<!-- diagram-forge -->",
    "# 🔷 Diagram Forge — Architecture Analysis",
    "",
    graphSection(graph),
    "",
    gradeSection(bench),
  ];

  if (diff && diff.summary.severity !== "none") {
    sections.push("", diffSection(diff));
  } else if (diff) {
    sections.push("", "## ✅ No Architecture Changes", "", "This PR introduces no structural changes to the architecture.");
  }

  if (shareUrl) {
    sections.push("", `---`, `📊 **[View interactive diagram](${shareUrl})**`);
  }

  sections.push(
    "",
    "---",
    "<sub>Generated by [Diagram Forge](https://diagram-forge.dev) · Living architecture diagrams · Paid via ⚡ Lightning</sub>"
  );

  return sections.join("\n");
}
